language: java

jdk:
  - openjdk11

script:
  - chmod u+x ./.ci/script.sh 
  - chmod u+x mvnw
  - ./.ci/script.sh

env:
 global:
   - CODECOV_TOKEN="2f735df4-a049-416a-92d3-630f6bc31d52"

after_success:
  - bash <(curl -s https://codecov.io/bash)
