ignore:
	- "br/com/moviesbattle/dto/data/*.java"
	- "br/com/moviesbattle/exception/*.java"
	- "br/com/moviesbattle/config/*.java"
	- "br/com/moviesbattle/repository/*.java"
	- "br/com/moviesbattle/repository/specification/*.java"
