version: "3"
services:
  movies-battle:
    image: muriloalvesdev/moviesbattle
    network_mode: bridge
    container_name: moviesbattle
    expose:
      - 8081
    ports:
      - 8081:8081
    restart: unless-stopped
